version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependências..."
      - yum install -y jq curl unzip
      - curl -LO https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip -d /usr/local/bin/
      - echo "Versões: Terraform $(terraform --version | head -n1), jq $(jq --version)"

  pre_build:
    commands:
      - echo "=== INÍCIO DA VALIDAÇÃO FIREFLY ==="
      - |
        echo "Verificando segredos..."
        [ -z "$AWS_ACCOUNT_ID" ] && { echo "Variável AWS_ACCOUNT_ID não definida"; exit 1; }
        
        # Autenticação
        AUTH_PAYLOAD='{"accessKey":"'"$FIREFLY_ACCESS_KEY"'","secretKey":"'"$FIREFLY_SECRET_KEY"'"}'
        AUTH_RESPONSE=$(curl -s -X POST "https://api.firefly.ai/api/v1.0/login" \
          -H "Content-Type: application/json" \
          -d "$AUTH_PAYLOAD")
        
        ACCESS_TOKEN=$(echo "$AUTH_RESPONSE" | jq -r '.accessToken')
        [ "$ACCESS_TOKEN" = "null" ] && { echo "Erro na autenticação"; exit 1; }

        # Payload sem jq complexo
        PAYLOAD='{
          "assetType": "terraform_plan",
          "assetId": "infra-'"$AWS_ACCOUNT_ID"'-'"$(date +%s)"'",
          "iacType": "terraform",
          "provider": "aws",
          "accountNumber": "'"$AWS_ACCOUNT_ID"'",
          "plan": '"$(cat tfplan.json)"'
        }'

        # Chamada à API
        RESPONSE=$(curl -s -X POST "https://api.firefly.ai/api/v1.0/codify" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD")

        STATUS=$(echo "$RESPONSE" | jq -r '.codifiedResult.status')
        [ "$STATUS" != "approved" ] && { echo "Rejeitado: $(echo "$RESPONSE" | jq -r '.codifiedResult.message')"; exit 1; }

  build:
    commands:
      - echo "=== APLICANDO INFRAESTRUTURA ==="
      - terraform apply -auto-approve tfplan

env:
  secrets-manager:
    FIREFLY_ACCESS_KEY: "arn:aws:secretsmanager:us-east-1:458745156302:secret:firefly/credentials-labana2025-RksHlQ:access-key::"
    FIREFLY_SECRET_KEY: "arn:aws:secretsmanager:us-east-1:458745156302:secret:firefly/credentials-labana2025-RksHlQ:secret-key::"
    AWS_ACCOUNT_ID: "arn:aws:secretsmanager:us-east-1:458745156302:secret:aws-account-8MKO9x:account-id::"