version: 0.2

phases:
  install:
    commands:
      # 1. Instala dependências
      - yum update -y
      - yum install -y unzip tar gzip
      - yum install -y curl 

      - curl -O https://gofirefly-prod-iac-ci-cli-binaries.s3.amazonaws.com/fireflyci/latest/fireflyci_Linux_x86_64.tar.gz
      - tar -xf fireflyci_Linux_x86_64.tar.gz
      - chmod a+x fireflyci
      - ./fireflyci post-plan -l plan_log.jsonl -f plan_output.json --workspace WORKSPACEana123


      
      # 2. Instala Terraform
      - TERRAFORM_VERSION="1.5.7"
      - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin/

  build:
    commands:

      # Validação para Terraform
      - echo "Gerando plano do Terraform..."
      - cd terraform && terraform init && terraform plan -json -out=tf.plan > plan_log.jsonl && terraform show -json tf.plan > plan_output.json 
      



env:
  secrets-manager:
    FIREFLY_ACCESS_KEY: "firefly/credentials-labana2025:access-key"
    FIREFLY_SECRET_KEY: "firefly/credentials-labana2025:secret-key"