version: 0.2

phases:
  install:
    commands:
      - echo "Verificando ferramentas instaladas..."
      - curl --version
      - yum install -y jq



  pre_build:
    commands:
      - echo "=== TESTE SIMPLES DA API FIREFLY ==="
      
      # Autenticação
      - |
        echo "1. Obtendo token de acesso..."
        AUTH_RESPONSE=$(curl -s -X POST "https://api.firefly.ai/api/v1.0/login" \
          -H "Content-Type: application/json" \
          -d "{\"accessKey\":\"$FIREFLY_ACCESS_KEY\",\"secretKey\":\"$FIREFLY_SECRET_KEY\"}")
        
        echo "Resposta da autenticação:"
        echo "$AUTH_RESPONSE" | jq .

        ACCESS_TOKEN=$(echo "$AUTH_RESPONSE" | jq -r '.accessToken')
        if [ -z "$ACCESS_TOKEN" ]; then
          echo "❌ Falha na autenticação"
          exit 1
        fi

      # Chamada de teste
      - |
        echo "2. Chamando endpoint /codify com payload mínimo..."
        TEST_PAYLOAD='{
          "assetType": "terraform_plan",
          "assetId": "teste-123",
          "iacType": "terraform",
          "provider": "aws",
          "accountNumber": "458745156302"
        }'

        RESPONSE=$(curl -s -X POST "https://api.firefly.ai/api/v1.0/codify" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "Content-Type: application/json" \
          -d "$TEST_PAYLOAD")

        echo "Resposta da API:"
        echo "$RESPONSE" | jq .

env:
  secrets-manager:
    FIREFLY_ACCESS_KEY: "firefly/credentials-labana2025:access-key"
    FIREFLY_SECRET_KEY: "firefly/credentials-labana2025:secret-key"